import React from 'react'
import AdminNavBar from '../components/adminNavbar/AdminNavbar'

export const metadata = {
  title: 'Admin',
  description: 'Generated by Batuk',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AdminNavBar />
        {children}</body>
    </html>
  )
}
