import React from 'react'

export const metadata = {
  title: 'Admin',
  description: 'Generated by Batuk',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
